# Generated by Django 3.2.9 on 2021-11-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_article"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "countries"},
        ),
    ]
