# Generated by Django 3.2.9 on 2021-11-22 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_country_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="news.country",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="country",
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
